version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: autocomplete
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    networks:
      - app-network

  java-backend:
    build:
      context: ./AutocompleteBackend
      dockerfile: Dockerfile
    environment:
      DB_URL: jdbc:mysql://mysql:3306/autocomplete
      DB_USER: root
      DB_PASSWORD: root
    depends_on:
      - mysql
    ports:
      - 4567:4567
    networks:
      - app-network

  frontend:
    build:
      context: ./autocomplete-frontend
      dockerfile: Dockerfile
    environment:
       NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  db:
    driver: local