version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: autocomplete
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    networks:
      - backend-network

  java-backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_URL: jdbc:mysql://mysql:3306/autocomplete
      DB_USER: root
      DB_PASSWORD: root
    depends_on:
      - mysql
    ports:
      - 4567:4567
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
volumes:
  db:
    driver: local